apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync
spec:
  providers:
  - name: keycloak
    keycloak:
      ca:
        kind: ConfigMap
        name: keycloak-ca
        namespace: openshift-config
      loginRealm: openshift-IdP
      realm: openshift-IdP
      credentialsSecret:
        name: keycloak-group-sync
        namespace: oidc-provider
      url: https://keycloak-server-oidc-provider.apps.sno-cluster.okd-sno.dedalus.red.com